{{- if .Values.consul.enabled }}
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: {{ include "guestbook.fullname" . }}
spec:
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
    v2:
      filter: 'Service.Meta.version == v2'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: {{ include "guestbook.fullname" . }}
spec:
  splits:
    - weight: 50
      serviceSubset: "v1"
    - weight: 50
      serviceSubset: "v2"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: {{ include "guestbook.fullname" . }}
spec:
  routes:
    - match: 
        http:
          queryParam:
            - name: canary
              exact: "true"
      destination:
        serviceSubset: "v2"
{{- end }}