apiVersion: v2
name: guestbook
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 5.0.0
dependencies:
  - condition: redis.enabled
    name: redis
    version: 17.6.x
    repository: https://charts.bitnami.com/bitnami
keywords:
- php
- guestbook
- redis
maintainers:
- email: daeung@plateer.com
  name: daeungkim