{{- if .Values.redis.master.persistence.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "guestbook.fullname" . }}-restore
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: restore
          image: redis:alpine3.11
          command:
            - /bin/sh
            - -c
            - rm -rf /data/dump.rdb; mv /data/backup/dump-{{ .Release.Revision }}.rdb /data/dump.rdb
          volumeMounts:
            - name: redis-data
              mountPath: /data
      restartPolicy: OnFailure
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-{{ template "redis.fullname" . }}-master-0
{{- end }}