apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guestbook.fullname" . }}-backup-configmap
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
data:
  backup.sh: |
    #!/bin/bash
    cd /data
    redis-cli -h  {{ template "redis.fullname" . }}-master save
    mkdir -p /data/backup
    mv /data/dump.rdb /data/backup