{{- if .Values.ingress.enabled -}}
{{- $fullName := include "guestbook.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ $fullName }}
spec:
  controller: "ingress.k8s.aws/alb"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ tpl .Values.ingress.annotations . | nindent 4 | trim }}
  {{- end }}  
spec:
  ingressClassName: {{ $fullName }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range (.paths | default (list "/")) }}
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 443
            path: {{ . }}
            pathType: Prefix
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}